default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: katie
  password: 040846
  pool: 5


development:
  <<: *default
  database: nn_academy_quest_development

test:
  <<: *default
  database: nn_academy_quest_test


# production:
#   primary: &primary_production
#     <<: *default
#     database: nn_academy_quest_production
#     username: nn_academy_quest
#     password: <%= ENV["NN_ACADEMY_QUEST_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: nn_academy_quest_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: nn_academy_quest_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: nn_academy_quest_production_cable
#     migrations_paths: db/cable_migrate
