default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: katie
  password: 040846
  pool: 5


development:
  <<: *default
  database: nn_academy_quest_development

test:
  <<: *default
  database: nn_academy_quest_test


production:
#   primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

